### PR TITLE
Add type definitions for TypeScript

### PR DESCRIPTION
**Pull request by mattiasw**
@bpatrik I have never used TypeScript but I tried to add type definitions for it. If you have the time, please have a look to see if this is what you want. I also know of DefinitelyTyped but as I understand it it's preferred to include the definitions in the package itself if possible.

### CODE REVIEW

**Comment by bpatrik** [comment]
Hi,

It looks nice.
I tested it, it seems working.
You can also consider adding the possible tags too. 
I have a list of them:
https://github.com/bpatrik/ts-exif-parser/blob/master/lib/ExifData.ts
Feel free to use it. Or I can make a PR for you too.

----------------
Some personal remarks, feel free to ignore them:
As far as I understand its better if your lib includes the definitions. I never created one for a `js` file. I'm only using TypeScript and ts->js compilation process has an option to auto create one.
This is actually also an option for you: rewrite `.js` to `.ts`.  It should mostly work as you write is ea6 (webpack is tricky sometimes) You might also be able to drop babel, since typescript can compile  to es5.

**Comment by mattiasw** [comment]
I did a new take and added the tags too. I noticed some strange implementation details though. I would probably made other choices today, but for now this is how it is. Specifically strings are always wrapped in an array, and IPTC tags will always be an array of numbers. I guess it would be possible to rewrite ExifReader to convert at an earlier stage but it would break backwards compatibility and need more work than this.

Please have a look at this version and tell me if anything looks too strange. :-)

**Comment by bpatrik** [comment]
Hi,
I've quickly tested it. It seems to be working. Thank you for your work!

Personally I don't mind if the raw data is there too as far as I does not introduce significant some computation overhead in it.

**Comment by mattiasw** [comment]
Merged. Will also publish the npm package.

**Comment by bpatrik** [comment]
Thank you!

**Pull request merged**
