### PR TITLE
Remove dependency of jDataView

### PR DESCRIPTION
**Pull request by mattiasw**
@bpatrik Would you like to try this one out without using jDataView? I realized DataView has been supported in Node since 0.12 and it should probably just work (I started this project before 0.12 was out). That said, I still did some changes to make it easier and clearer.

### CODE REVIEW

**Comment by bpatrik** [comment]
Hi,

I've tested it. It works like charm.
Thank you very much for your quick work!

Is it maybe also possible at some point to avoid `global.DOMParser = require('xmldom').DOMParser;` too?
My concern is mostly that I have to use it like this from a `ts` project:
```typescript
// @ts-ignore
global.DOMParser = require('xmldom').DOMParser;
const ExifReader = require('exifreader');
```

instead of this:
```typescript
import * as ExifReader from 'exifreader';
```

or even better like this:
```typescript
import {ExifReader} from 'exifreader';
```

**Comment by mattiasw** [comment]
@bpatrik The XMLDOM part was tricky but I think I got it working now. It still uses it in the background but you as a user don't need to care. Have a look. (The tricky part was differentiating between browser and Node environments and only importing it when needed.)

**Comment by bpatrik** [comment]
@mattiasw Great!  Seems to be working, thank you very much for the quick reply!

**Comment by mattiasw** [comment]
Nice! This feels much better to be honest. Thanks for the input!

**Pull request merged**
