### PR TITLE
Fix running test suite on Windows

### LINKED ISSUE #43: Make sure all dev scripts work on Windows
At least running the tests don't work on a Windows setup.

### PR DESCRIPTION
**Pull request by mattiasw**
Fixes #43.

@SaintFlipper If you want to have a look. I tried it on Windows though, so it should be okay.

### CODE REVIEW

**Comment by SaintFlipper** [comment]
Thanks Mattias
I only just had a chance to run the tests. There seem to be several
dependencies which I didn't have and had to resolve step by step with each
successive error.
Below are the errors reported on each successive "npm test" run and what
needed to be installed to get past that error.
Maybe it's assumed that all these dependencies are present for most Node.js
dev installations, but it would be useful to have them listed in the readme
for people like me who are primarily client side developers rather than
Node. Essentially the dependencies I needed to install were: *cross-env*,
*mocha*, *babel-core*, *babel-plugin-rewire*, *chai*, *xmldom* (or other
DOMParser implementation).

===================

1. npm test

ERROR:
'cross-env' is not recognized as an internal or external command,
operable program or batch file.

SOLUTION:
npm install --save-dev cross-env

2. npm test

ERROR:
'mocha' is not recognized as an internal or external command,
operable program or batch file.

SOLUTION:
npm install mocha

3.  npm test

ERROR:
module.js:471
    throw err;
    ^
Error: Cannot find module 'babel-core/register'

SOLUTION:
npm install babel-core

4. npm test

ERROR:
          throw new ReferenceError(messages.get("pluginUnknown", plugin,
loc, i, dirname));
          ^
ReferenceError: Unknown plugin "rewire" specified in
"D:\\Proj\\3rdp\\ExifReader\\.babelrc.env.test" at 0, attempted to resolve
relative to "D:\\Proj\\3rdp\\ExifReader"

SOLUTION:
npm install babel-plugin-rewire

5. npm test

ERROR:
       throw e;
        ^

Error: Couldn't find preset "env" relative to directory
"D:\\Proj\\3rdp\\ExifReader"

SOLUTION:
npm install babel-preset-env


6. npm test

ERROR:
module.js:471
    throw err;
    ^
Error: Cannot find module 'chai'

SOLUTION:
npm install chai

7. npm test

ERROR:
Most tests run exception for DOMParser/XMP parts:

 DOMParser (for XMP) errors during test run
 dom-parser
   √ should return DOMParser if it is globally defined
   1) should return DOMParser from the XMLDOM module if available

SOLUTION:
npm install xmldom

8. npm test

SUCCESS:
All tests now run
  358 passing (2s)

**Comment by mattiasw** [comment]
Hi! Sorry to hear you has such trouble getting it to work. However, the only thing you should need to do is run `npm install` in the directory and all those dependencies will be automatically installed. They are listed in the `package.json` file. The only things that one need to have before starting is `node` and `npm`. I just tried it in a clean directory and it worked fine.

**Comment by SaintFlipper** [comment]
Thanks Mattias. It was my own fault. I'd cloned the new version into a
separate directory but hadn't done the npm install there, only the clone.

**Comment by mattiasw** [comment]
:+1: Thanks for helping out testing.

**Pull request merged**
