### PR TITLE
Fix type of DateTimeOriginal property

### LINKED ISSUE #231: Typescript: DateTimeOriginalis has wrong type of StringArrayTag
### Description

Definition of `DateTimeOriginal` is not correct. It is declared as `StringArrayTag` but `value` is supposed to be a string instead of Array. Also there is `attributes` property instead of `id`.

**Additional details**

- ExifReader version: 4.11.1
- Node version: v16.17.0

Used this resource to confirm that this is supposed to be a string:

https://exiftool.org/TagNames/EXIF.html

**How to reproduce**

jolla

### PR DESCRIPTION
**Pull request by cybertino**
### Description

Changed type of `DateTimeOriginal ` property to fix #231 .

### CODE REVIEW

**Comment by cybertino** [comment]
Thanks @mattiasw! Should be fixed now.

**Review by mattiasw — COMMENTED** [review]
It seems like it can only handle explicitly specified tags now. But XMP tags can be named whatever. And it also can't handle PNG tags which can also be named anything (the removed test would show this issue). The latter is probably just a matter of also adding PngTag to the Tags type, but I don't know how to solve the former problem.

But I think the previous code with `|` was more correct. It's just that Tags only specify Exif tags but as mentioned, tag names can be anything.

I've added more type tests and this is the exif-reader.ts file I have now. You can run the type tests with `npm run test:types`.
```
import {load} from '../../exif-reader.js';

load('', {includeUnknown: true});
load('', {length: 1024});
load('', {expanded: false, includeUnknown: true, length: 1024});

const tags = await load('');
const expandedTags = await load('', {expanded: true});

/////////
// Exif
if (tags['DateTimeOriginal']) {
    if ('id' in tags['DateTimeOriginal']) {
        tags['DateTimeOriginal'].id === 0x9003;
    }
    if (Array.isArray(tags['DateTimeOriginal'].value)) {
        tags['DateTimeOriginal'].value[0] === '2014:09:21 16:00:56';
    }
    tags['DateTimeOriginal'].description === '2014:09:21 16:00:56';
}
if (expandedTags['exif']?.['DateTimeOriginal']) {
    if ('id' in expandedTags['exif']['DateTimeOriginal']) {
        expandedTags['exif']['DateTimeOriginal'].id === 0x9003;
    }
    if (Array.isArray(expandedTags['exif']['DateTimeOriginal']?.value)) {
        expandedTags['exif']['DateTimeOriginal'].value[0] === '2014:09:21 16:00:56';
    }
    expandedTags['exif']['DateTimeOriginal'].description === '2014:09:21 16:00:56';
}

////////
// XMP
if (expandedTags['xmp']?.['DateTimeOriginal']) {
    expandedTags['xmp']['DateTimeOriginal'].attributes['some-key'] === 'some value';
    expandedTags['xmp']['DateTimeOriginal'].attributes['some-key'] === 'some value';
    // @ts-expect-error
    expandedTags['xmp']['DateTimeOriginal'].attributes === 'some value';
    expandedTags['xmp']['DateTimeOriginal'].value === '2014:09:21 16:00:56';
}
if (tags['DateTimeOriginal']) {
    if ('attributes' in tags['DateTimeOriginal']) {
        tags['DateTimeOriginal'].attributes['some-key'] === 'some value';
    }
}
tags['DateTimeOriginal']?.value === '2014:09:21 16:00:56';
if ('SomeNonExifTag' in tags) {
    tags['SomeNonExifTag'].value === 'value';
}

////////
// PNG
if ('Color Type' in tags) {
    tags['Color Type'].description === 'Grayscale';
}

expandedTags.png?.['Color Type']?.description === 'Grayscale';
expandedTags.png?.['Pixel Units']?.value === 1;
// @ts-expect-error
expandedTags.png?.['Pixel Units']?.value === 'a string';
expandedTags.png?.['Pixel Units']?.description === 'meters';
// @ts-expect-error
expandedTags.png?.['Color Type']?.description === 'A non-color type value';
expandedTags.png?.['Custom Tag Name']?.description === 'Should work';
```

**Comment by mattiasw** [comment]
I've been thinking some more about this and I'm wondering if we should just make the combined-tags type simpler. I made a try in another PR, what do you think? https://github.com/mattiasw/ExifReader/pull/233

**Comment by cybertino** [comment]
Thanks @mattiasw! Thanks a lot for your quick replies and sorry for the delayed response. I saw the PR you created and I think the rest you created is definitely more comprehensive. The type definitions cover more scenarios now which is good as well but at the same time some values that have a specific type look generic. For example:

```ts
tags["DateTimeOriginal"].value[0] === "2014:09:21 16:00:56";
```

The `tags["DateTimeOriginal"].value[0] ` suggests to be `string | number | XmpTag`. We have to cast the value even though we know that it is a `string`.

Saying this I understand a complexity of the problem.

**Comment by cybertino** [comment]
I made some updates using changes from your PR. One question I am not sure about is whether XMP tag has a value of `string` instead of recursive `XmpTag` in case property matched to EXIF one.

If this is not the case (i.e. XMP tag can be whatever regardless of what the EXIF one is) we can just simply change to:

```ts
[K in keyof ExifTags]: ExifTags[K] | XmpTag;
```

The advantage of having it as `XmpTagValue` is that Typescript is clever enough to resolve the value type to `string` in case of Exif prop being `StringArrayTag`.

**Comment by mattiasw** [comment]
> One question I am not sure about is whether XMP tag has a value of `string` instead of recursive `XmpTag` in case property matched to EXIF one.

Here is where the issue is I think. We can't actually know it is a string. It probably will be, at least in the case with `DateTimeOriginal`, but we can't know for certain for the combined tags. If one wants better type hints it's definitely advised to use `{expanded: true}`. Then we can know.

So, I would say we have to allow it to be able to be both a string and a recursive `XmpTag` even when it matches an Exif tag name.

Otherwise I like what I'm seeing. :-)

**Comment by cybertino** [comment]
Alright, I changed `Tags` props to use `XmpTag` like I mentioned above.

**Pull request merged**
